title: sourceflow.dev
description: Beautiful websites and cross-platform apps
email: andrew@sourceflow.dev
author: Andrew Engelbrecht
logo: assets/img/bird-logo-512-bg.png
url: https://sourceflow.dev

navlinks:
  - name: About
    url: /about
  - name: Apps
    url: /apps

homelinks:
  - name: About
    url: /about
  - name: Open Alert Viewer
    url: /apps/open-alert-viewer
  - name: Kaya
    url: /apps/kaya
  - name: swirlnet
    url: /apps/swirlnet

sociallinks:
  - name: github
    icon: github.svg
    url: https://github.com/leaf-node/
  - name: mastodon
    icon: mastodon.svg
    url: https://mastodon.social/@vegantacos
  - name: email
    icon: email.svg
    url: mailto:andrew@sourceflow.dev
  - name: buymeacoffee
    icon: buymeacoffee.svg
    url: https://buymeacoffee.com/sourceflow.dev

defaults:
  - scope:
      path: "" # all files
    values:
      layout: default
      image: assets/img/bird-logo-512-bg.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - about
  - apps

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
