title: sourceflow.dev
description: Beautiful websites and cross-platform apps
email: andrew@sourceflow.dev
author: Andrew Engelbrecht
logo: assets/img/bird-logo-512-bg.png
url: https://sourceflow.dev

navlinks:
  - name: Apps
    url: /apps
  - name: Resume
    url: /assets/pdf/Andrew-Engelbrecht-resume.pdf

homelinks:
  - name: About
    url: /about
  - name: Open Alert Viewer
    url: /apps/open-alert-viewer
  - name: Kaya
    url: /apps/kaya
  - name: swirlnet
    url: /apps/swirlnet

sociallinks:
  - name: codeberg
    icon: codeberg.svg
    url: https://codeberg.org/leaf-node/
  - name: mastodon
    icon: mastodon.svg
    url: https://mastodon.social/@vegantacos
  - name: email
    icon: email.svg
    url: mailto:andrew@sourceflow.dev
  - name: linkedin
    icon: linkedin.png
    url: https://www.linkedin.com/in/andrew-engelbrecht/
  - name: buymeacoffee
    icon: buymeacoffee.svg
    url: https://buymeacoffee.com/sourceflow.dev

defaults:
  - scope:
      path: "" # all files
    values:
      layout: default
      image: assets/img/bird-logo-512-bg.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - about
  - apps

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
